version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install -r requirements.txt
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
